"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, ChevronDown, ChevronLeft, ChevronRight, Download, ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  CANARIES, CODES_LABEL, CONFIG, INDEX_COLS, MIGRATION_SQL, Q1_HASHED, QOR_REWRITTEN, QOR_SQL, ROLLBACK_SQL, TOOLS, WRITE_COST, ms, run,
} from "@/lib/facts";
import { bellman, speedupPct, tar } from "@/lib/logic";
import { RECORD_LEDGER, STAGES, useRun, type StageId } from "@/lib/store";
import { CopyButton, Pip, Source, SqlBlock, Stat, save } from "./bits";

const H = ({ children }: { children: React.ReactNode }) => <h3 className="mb-2 mt-5 text-sm font-semibold text-slate-900 first:mt-0">{children}</h3>;
const seg = (on: boolean) => cn("h-7 rounded px-2.5 text-xs", on ? "bg-slate-900 text-white" : "text-slate-600 hover:bg-slate-100");

// ---- Postgres source -------------------------------------------------------------------
function SourceSheet() {
  return (
    <>
      <H>Q1 is logged as slow on pg-prod</H>
      <SqlBlock text={Q1_HASHED} file="q1.sql" />
      <Source>Shown as the AI side receives it ({CODES_LABEL}). The real query stays on the private network.</Source>
      <div className="mt-3 grid grid-cols-2 gap-2">
        <Stat label="Q1 mean before" value={ms(run.q1.mean_ms_before)} note="pg-prod, no index" />
        <Stat label="slow threshold" value={`${run.q1.slow_threshold_ms} ms`} note="config.yaml workload.slow_query_ms, human-approved" />
        <Stat label="hero table rows" value={run.dataset.hero_table_rows.toLocaleString("en-US")} note="synthetic demo retail DB, generated by db/" />
        <Stat label="hero table size" value={`${run.dataset.hero_table_size_mb} MB`} note="on disk" />
      </div>
    </>
  );
}

// ---- Gateway ---------------------------------------------------------------------------
function GatewaySheet() {
  const ledger = RECORD_LEDGER;
  const [canary, setCanary] = useState<number | null>(null);
  const [q, setQ] = useState("");
  const [dest, setDest] = useState<"all" | "ai" | "llm">("all");
  const rows = ledger.filter(
    (r) => (dest === "all" || r.destination === dest) && `${r.id} ${r.destination} ${r.sha256}`.toLowerCase().includes(q.toLowerCase()),
  );
  const c = canary === null ? null : CANARIES[canary];
  return (
    <>
      <H>{run.privacy.canary_hits} of {run.privacy.canaries_planted} canaries left the private network</H>
      <div className="grid grid-cols-4 gap-1.5">
        {CANARIES.map(([id], i) => (
          <button key={i} onClick={() => setCanary(i === canary ? null : i)}
            className={cn("flex items-center gap-1 rounded-md border px-1.5 py-1 font-mono text-[10.5px]",
              i === canary ? "border-slate-900 bg-slate-900 text-white" : "border-slate-200 bg-white/70 text-slate-700 hover:bg-white")}>
            <Pip tone="ok" /> {id.slice(3)}
          </button>
        ))}
      </div>
      {c ? (
        <div className="inset-field mt-2 space-y-1 p-3 text-xs text-slate-700">
          <div className="font-mono text-slate-900">{c[0]}</div>
          <div>kind: <span className="font-mono">{c[1]}</span></div>
          <div>placement: {c[2]}</div>
          <div className="flex items-center gap-1.5 text-emerald-700"><ShieldCheck className="size-3.5" /> 0 hits in {run.privacy.payloads} outbound payloads of {run.run_id}</div>
          <Source>The id is the first 8 hex of SHA-256 of the planted value (db/canaries.py). The value itself is never shown. The scanner also blocks any 6-character fragment.</Source>
        </div>
      ) : (
        <Source>Click a canary to see where it is planted. Hit count is the run total; per-canary hits are not split out in the run record, and the total is 0.</Source>
      )}

      <H>What leaves the private network for Q1</H>
      <SqlBlock text={Q1_HASHED} />
      <Source>
        {`${CODES_LABEL[0].toUpperCase()}${CODES_LABEL.slice(1)}: real ones are t_ or c_ plus the first ${CONFIG.hexChars} hex of HMAC-SHA256 under the key in .env, which never leaves the private side. Values become ?.`}{" "}
        <Link href="/hashing" className="text-blue-700 underline">Hash your own SQL in the visualizer</Link>.
      </Source>

      <H>Outbound ledger</H>
      <div className="mb-2 flex flex-wrap items-center gap-2">
        <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search id, destination or sha256"
          className="inset-field h-8 flex-1 px-2 text-xs outline-none focus:border-blue-500" />
        <div className="flex rounded-md border border-slate-200 bg-white/70 p-0.5">
          {(["all", "ai", "llm"] as const).map((d) => <button key={d} className={seg(dest === d)} onClick={() => setDest(d)}>{d}</button>)}
        </div>
      </div>
      <div className="inset-field max-h-64 overflow-auto">
        <table className="w-full text-left text-xs">
          <thead className="sticky top-0 bg-slate-50 text-slate-500">
            <tr><th className="px-2 py-1.5 font-medium">payload</th><th className="px-2 font-medium">to</th><th className="px-2 font-medium">count</th><th className="px-2 font-medium">sha256</th><th className="px-2 font-medium">canary hits</th></tr>
          </thead>
          <tbody className="font-mono text-slate-800">
            {rows.map((r, i) => (
              <tr key={i} className="border-t border-slate-200/70">
                <td className="px-2 py-1.5">{r.id}</td><td className="px-2">{r.destination}</td><td className="px-2">{r.count}</td>
                <td className="max-w-32 truncate px-2" title={r.sha256}>{r.sha256}</td>
                <td className="px-2"><span className="inline-flex items-center gap-1"><Pip tone={r.canaryHits ? "bad" : "ok"} />{r.canaryHits}</span></td>
              </tr>
            ))}
            {rows.length === 0 && <tr><td colSpan={5} className="px-2 py-3 text-center text-slate-400">no rows match</td></tr>}
          </tbody>
        </table>
      </div>
      <Source>{`The run record's totals: ${run.privacy.payloads} payloads, ${run.privacy.llm_payloads} of them to the LLM. Per-payload ids and hashes stay in the operator's ledger.`}</Source>
    </>
  );
}

// ---- Miner and estimator ---------------------------------------------------------------
function MinerSheet() {
  return (
    <>
      <H>The miner proposes one composite index for Q1</H>
      <Stat label="recommended index" value={INDEX_COLS} note={`${run.search.recommended_columns} columns, equality column first; ${CODES_LABEL}`} />
      <p className="mt-3 text-xs leading-relaxed text-slate-600">
        FP-Growth runs over the hashed slow templates, weighting each by calls x latency. One value of the equality column holds 30.01% of the hero table&apos;s rows (db/NOTES.md), so the equality column leads.
      </p>
      <Source>The candidate list and supports of {run.run_id} are not in the run record.</Source>
    </>
  );
}

function GnnSheet() {
  return (
    <>
      <div className="rounded-md border border-amber-300/70 bg-amber-50/80 px-3 py-2 font-mono text-xs text-amber-900">{run.search.estimator_label}</div>
      <H>Predicted Q1 times used by the search</H>
      <div className="grid grid-cols-2 gap-2">
        <Stat label="predicted before" value={`${run.search.predicted_before_ms} ms`} note="Postgres cost x calibration" />
        <Stat label="predicted after" value={`${run.search.predicted_after_ms} ms`} note="same estimator, with the index" />
      </div>
      <H>GNN reference loop (not serving)</H>
      <table className="inset-field w-full text-xs">
        <tbody className="font-mono text-slate-800">
          {[["GNN", "2.47"], ["Postgres baseline", "2.54"], ["scikit-learn GBT", "1.56"]].map(([k, v]) => (
            <tr key={k} className="border-t border-slate-200/70 first:border-0"><td className="px-3 py-1.5 font-sans text-slate-600">{k}</td><td className="px-3 text-right">{v}</td></tr>
          ))}
        </tbody>
      </table>
      <Source>Median q-error on 40 test plans from the 200-plan sample: too small to conclude. Trained weights are not delivered, so serving uses the Postgres baseline.</Source>
    </>
  );
}

// ---- RL search -------------------------------------------------------------------------
const ACTIONS = ["add_index", "rewrite", "partition", "STOP"] as const;
const CHOICES = ACTIONS.slice(0, 3);
const STATES = [[], ["add_index"], ["rewrite"], ["partition"], ["add_index", "rewrite"], ["add_index", "partition"], ["rewrite", "partition"], ["add_index", "rewrite", "partition"]] as string[][];
const key = (s: string[]) => `{${s.join(", ")}}`;
const fresh = () => Object.fromEntries(STATES.flatMap((s) => ACTIONS.map((a) => [`${key(s)}|${a}`, CONFIG.qInit])));

function RlSheet() {
  const [q, setQ] = useState<Record<string, number>>(fresh);
  const [cell, setCell] = useState<[number, number]>([0, 0]);
  const [reward, setReward] = useState(0.5);
  const [alpha, setAlpha] = useState(CONFIG.alpha);
  const [gamma, setGamma] = useState(CONFIG.gamma);
  const valid = (s: string[], a: string) => a === "STOP" || !s.includes(a);
  const [si, ai] = cell;
  const s = STATES[si];
  const a = ACTIONS[ai];
  const cur = q[`${key(s)}|${a}`];
  // rl/search.py: STOP has target 0; otherwise the best next value over the options left in s'.
  const next = [...s, a].sort((x, y) => CHOICES.indexOf(x as never) - CHOICES.indexOf(y as never));
  const maxNext = a === "STOP" ? 0 : Math.max(...ACTIONS.filter((b) => valid(next, b)).map((b) => q[`${key(next)}|${b}`]));
  const r = a === "STOP" ? 0 : reward;
  const updated = bellman(cur, r, maxNext, alpha, gamma);
  const vals = Object.values(q);
  const lo = Math.min(...vals), hi = Math.max(...vals);
  const shade = (v: number) => (hi === lo ? 0.12 : 0.08 + (0.8 * (v - lo)) / (hi - lo));
  const slider = (label: string, v: number, set: (x: number) => void, min: number, max: number, note: string) => (
    <label className="block text-xs text-slate-600">
      <span className="flex justify-between"><span>{label}</span><span className="font-mono text-slate-900">{v.toFixed(2)}</span></span>
      <input type="range" min={min} max={max} step={0.01} value={v} onChange={(e) => set(Number(e.target.value))} className="w-full accent-blue-600" />
      <Source>{note}</Source>
    </label>
  );
  return (
    <>
      <Source>{run.run_id}: {run.search.label}. Its Q-table is not in the run record.</Source>
      <H>Q-table sandbox</H>
      <Source>Every cell starts at config.yaml rl.q_init {CONFIG.qInit.toFixed(1)}. Values change only when you apply an update below. Shade scales with Q (darker is higher).</Source>
      <div className="mt-2 overflow-x-auto">
        <table className="w-full border-separate border-spacing-0.5 text-[11px]">
          <thead><tr><th className="text-left font-medium text-slate-500">state</th>{ACTIONS.map((x) => <th key={x} className="font-mono font-medium text-slate-500">{x}</th>)}</tr></thead>
          <tbody>
            {STATES.map((st, i) => (
              <tr key={i}>
                <td className="pr-1 font-mono text-slate-600">{key(st)}</td>
                {ACTIONS.map((x, j) => {
                  const v = q[`${key(st)}|${x}`];
                  const ok = valid(st, x);
                  const sh = shade(v);
                  return (
                    <td key={x}>
                      <button disabled={!ok} onClick={() => setCell([i, j])}
                        style={ok ? { backgroundColor: `rgba(15,23,42,${sh})`, color: sh > 0.45 ? "white" : "#0F172A" } : undefined}
                        className={cn("h-7 w-full rounded font-mono", !ok && "cursor-not-allowed bg-slate-100 text-slate-300", si === i && ai === j && "ring-2 ring-blue-600")}>
                        {ok ? v.toFixed(3) : "n/a"}
                      </button>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <H>Bellman update for Q({key(s)}, {a})</H>
      <div className="space-y-3">
        {a !== "STOP" && slider("reward R", reward, setReward, -1, 1, "Fractional time drop minus write and storage penalties, at most 1 (rl/NOTES.md). Set by you here.")}
        {slider("learning rate alpha", alpha, setAlpha, 0, 1, `config.yaml rl.alpha = ${CONFIG.alpha}`)}
        {slider("discount gamma", gamma, setGamma, 0, 1, `config.yaml rl.gamma = ${CONFIG.gamma}`)}
      </div>
      <div className="inset-field mt-3 p-3 font-mono text-xs leading-relaxed text-slate-800">
        <div>Q(s,a) &larr; Q(s,a) + alpha [R + gamma max Q(s&apos;,a&apos;) &minus; Q(s,a)]</div>
        <div className="text-slate-500">s&apos; = {a === "STOP" ? "terminal (STOP: target 0)" : key(next)}</div>
        <div>= {cur.toFixed(3)} + {alpha.toFixed(2)} &times; ({r.toFixed(2)} + {gamma.toFixed(2)} &times; {maxNext.toFixed(3)} &minus; {cur.toFixed(3)})</div>
        <div className="font-semibold text-slate-900">= {updated.toFixed(3)}</div>
      </div>
      <div className="mt-2 flex gap-2">
        <button className="h-8 rounded-md bg-slate-900 px-3 text-xs font-medium text-white hover:bg-slate-800" onClick={() => setQ({ ...q, [`${key(s)}|${a}`]: updated })}>Apply update</button>
        <button className="h-8 rounded-md border border-slate-200 bg-white/70 px-3 text-xs text-slate-700 hover:bg-white" onClick={() => setQ(fresh())}>Reset table</button>
      </div>
    </>
  );
}

// ---- LLM -------------------------------------------------------------------------------
function LlmSheet() {
  const [open, setOpen] = useState<string | null>(null);
  const recomputed = speedupPct(run.twin.before_ms, run.twin.after_ms);
  const checks: [string, string, string, boolean][] = [
    ["faster on the twin", `${run.twin.speedup_pct}%`, `recomputed here: (1 - ${run.twin.after_ms} / ${run.twin.before_ms}) x 100 = ${recomputed.toFixed(2)}%`, recomputed.toFixed(1) === run.twin.speedup_pct.toFixed(1)],
    ["index size", `${run.twin.storage_mb} MB`, `twin.storage_mb in the run record: ${run.twin.storage_mb}`, true],
    ["predicted after", ms(run.search.predicted_after_ms), `search.predicted_after_ms: ${run.search.predicted_after_ms}`, true],
    ["write cost per insert", `+${WRITE_COST.medianMs} ms`, `pgbench median of ${WRITE_COST.runs} runs on the twin (db/NOTES.md, 2026-10-03; not in this run record)`, true],
  ];
  return (
    <>
      <div className="grid gap-2 sm:grid-cols-3">
        <Stat label="model" value={run.llm.model} note={run.llm.provider} />
        <Stat label="tool calls" value={String(run.llm.tool_calls)} note="this run" />
        <Stat label="payloads to LLM" value={String(run.privacy.llm_payloads)} note={`${run.privacy.canary_hits} canary hits`} />
      </div>
      <H>The 8 tools the agent can call</H>
      <Source>{run.run_id} made {run.llm.tool_calls} calls; which tools, their order and their payloads are not in the run record. These are the declarations, verbatim from agent/tools.py.</Source>
      <div className="mt-2 space-y-1">
        {TOOLS.map((t, i) => (
          <div key={t.name} className="inset-field">
            <button className="flex w-full items-center gap-2 px-3 py-2 text-left" onClick={() => setOpen(open === t.name ? null : t.name)} aria-expanded={open === t.name}>
              <span className="font-mono text-[11px] text-slate-400">{i + 1}</span>
              <span className="font-mono text-xs text-slate-900">{t.name}</span>
              <ChevronDown className={cn("ml-auto size-3.5 text-slate-400 transition-transform", open === t.name && "rotate-180")} />
            </button>
            {open === t.name && (
              <div className="border-t border-slate-200/80 px-3 py-2">
                <p className="mb-2 text-xs text-slate-600">{t.description}</p>
                <pre className="overflow-x-auto font-mono text-[11px] text-slate-800">{JSON.stringify(t.parameters, null, 2)}</pre>
              </div>
            )}
          </div>
        ))}
      </div>
      <H>Number check</H>
      <Source>The agent&apos;s own {run.llm.numbers_checked} checked numbers are not stored in the run record. This table re-checks the run&apos;s headline figures in this page.</Source>
      <table className="inset-field mt-2 w-full text-xs">
        <tbody>
          {checks.map(([k, v, src, ok]) => (
            <tr key={k} className="border-t border-slate-200/70 align-top first:border-0">
              <td className="px-3 py-1.5 text-slate-600">{k}</td>
              <td className="px-2 py-1.5 font-mono text-slate-900">{v}</td>
              <td className="px-2 py-1.5 text-[11px] text-slate-500">{src}</td>
              <td className="px-2 py-1.5"><Pip tone={ok ? "ok" : "bad"} /></td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}

// ---- Twin ------------------------------------------------------------------------------
function TwinSheet() {
  const spans = useMemo(
    () => [
      { k: "prod Q1 mean, no index", v: run.q1.mean_ms_before, c: "bg-slate-400", d: "Mean on pg-prod at 10,000,000 rows. Measured, not on the twin." },
      { k: "twin before, no index", v: run.twin.before_ms, c: "bg-amber-500", d: `Median of ${run.twin.runs} runs on the statistical twin, measured while plan generation loaded the CPU.` },
      { k: "twin after, with index", v: run.twin.after_ms, c: "bg-emerald-500", d: `Median of ${run.twin.runs} runs with ${INDEX_COLS}. ${run.twin.speedup_pct}% faster than twin before.` },
      { k: "predicted before", v: run.search.predicted_before_ms, c: "bg-blue-300", d: run.search.estimator_label },
      { k: "predicted after", v: run.search.predicted_after_ms, c: "bg-blue-600", d: run.search.estimator_label },
    ],
    [],
  );
  const [hover, setHover] = useState(1);
  const max = 320;
  return (
    <>
      <H>Q1 drops from {ms(run.twin.before_ms)} to {ms(run.twin.after_ms)} on the twin</H>
      <div className="inset-field p-3">
        <div className="mb-1 flex gap-2 font-mono text-[10px] text-slate-400">
          <span className="w-[36%]">ms</span>
          <div className="flex flex-1 justify-between">{[0, 80, 160, 240, 320].map((t) => <span key={t}>{t}</span>)}</div>
          <span className="w-16" />
        </div>
        {spans.map((s, i) => (
          <div key={s.k} className={cn("flex cursor-default items-center gap-2 rounded py-1", hover === i && "bg-white/80")}
            onMouseEnter={() => setHover(i)} onClick={() => setHover(i)}>
            <span className="w-[36%] truncate text-[11px] text-slate-600">{s.k}</span>
            <div className="relative h-4 flex-1 rounded bg-slate-200/50">
              <div className={cn("h-full rounded", s.c)} style={{ width: `${(s.v / max) * 100}%` }} />
            </div>
            <span className="w-16 text-right font-mono text-[11px] text-slate-800">{ms(s.v)}</span>
          </div>
        ))}
        <div className="mt-2 border-t border-slate-200/80 pt-2 text-xs text-slate-700">
          <span className="font-medium">{spans[hover].k}:</span> {spans[hover].d}
          <Source>Plan node breakdown (scan types, per-node times) is not in the run record.</Source>
        </div>
      </div>
      <div className="mt-3 grid gap-2 sm:grid-cols-3">
        <Stat label="faster" value={`${run.twin.speedup_pct}%`} note="twin, median of 5" />
        <Stat label="index size" value={`${run.twin.storage_mb} MB`} note="twin disk" />
        <Stat label="twin fidelity, Q1" value="0.76" note="plan agreement, loaded machine (db/sandbox/fidelity.py)" />
      </div>
      <H>Result checksum</H>
      <div className="inset-field flex items-start gap-3 p-3">
        <span className={cn("mt-0.5 grid size-6 place-items-center rounded-full text-white", run.twin.checksum_match ? "bg-emerald-500" : "bg-red-500")}>
          <ShieldCheck className="size-3.5" />
        </span>
        <div className="text-xs text-slate-700">
          <div className="font-medium text-slate-900">{run.twin.checksum_match ? "Q1 gives the same result with and without the index" : "checksum mismatch"}</div>
          <Source>checksum_match = {String(run.twin.checksum_match)} in the run record (verify/checksum.py on the twin). The hash values themselves are not kept.</Source>
        </div>
      </div>
      <H>Rewrite diff</H>
      <Source>Q1&apos;s fix is an index, so its SQL does not change. Shown instead: the two-region report rewrite, status Verified by VeriEQL (bounded: 5 rows per table). Hand-rendered from rule or_same_column_to_in; values as ?; {CODES_LABEL}.</Source>
      <div className="mt-2 grid gap-2 sm:grid-cols-2">
        <div className="min-w-0"><div className="mb-1 text-[11px] text-slate-500">original</div><SqlBlock text={QOR_SQL} tone="del" /></div>
        <div className="min-w-0"><div className="mb-1 text-[11px] text-slate-500">rewritten</div><SqlBlock text={QOR_REWRITTEN} tone="add" /></div>
      </div>
    </>
  );
}

// ---- DBA -------------------------------------------------------------------------------
const pct = (base: number) => Math.round((WRITE_COST.medianMs / base) * 100);
const GATES: [string, string][] = [
  ["Twin execution verified", `${ms(run.twin.before_ms)} to ${ms(run.twin.after_ms)}, median of ${run.twin.runs} runs`],
  ["Result checksum identical", `checksum_match = ${run.twin.checksum_match}`],
  ["Zero canary leaks", `${run.privacy.canary_hits} of ${run.privacy.canaries_planted} in ${run.privacy.payloads} payloads`],
  ["Write cost reviewed", `+${WRITE_COST.medianMs} ms per insert against a ${WRITE_COST.baseLo} to ${WRITE_COST.baseHi} ms insert (${pct(WRITE_COST.baseHi)}% to ${pct(WRITE_COST.baseLo)}%, mostly the cold new index; db/NOTES.md)`],
];

function DbaSheet() {
  const { gates, toggleGate, authorize, authorizedAt } = useRun();
  const ready = gates.every(Boolean);
  const btn = "inline-flex h-8 items-center gap-1.5 rounded-md border border-slate-200 bg-white/80 px-3 text-xs text-slate-700 hover:bg-white";
  return (
    <>
      <Source>Reconstructed with gateway/approve.py&apos;s template for this run&apos;s index; the config_id is not in the run record; {CODES_LABEL}. The real files, with real names, come from POST /v1/approve on the operator side.</Source>
      <div className="mt-3 flex flex-wrap gap-2">
        <CopyButton text={MIGRATION_SQL} label="Copy migration" />
        <CopyButton text={ROLLBACK_SQL} label="Copy rollback" />
        <button className={btn} onClick={() => save(`blind-tuner-patch-${run.run_id}.tar`, tar({ "migration.sql": MIGRATION_SQL, "rollback.sql": ROLLBACK_SQL }) as BlobPart, "application/x-tar")}>
          <Download className="size-3.5" /> Download patch archive
        </button>
      </div>
      <H>migration.sql</H>
      <SqlBlock text={MIGRATION_SQL} file="migration.sql" />
      <H>rollback.sql</H>
      <SqlBlock text={ROLLBACK_SQL} file="rollback.sql" />
      <H>Pre-flight gates</H>
      <div className="space-y-1.5">
        {GATES.map(([k, ev], i) => (
          <label key={k} className="inset-field flex cursor-pointer items-start gap-2.5 p-2.5">
            <input type="checkbox" checked={gates[i]} onChange={() => toggleGate(i)} className="mt-0.5 size-4 accent-emerald-600" />
            <span className="text-xs"><span className="font-medium text-slate-900">{k}</span><br /><span className="text-slate-500">{ev}</span></span>
          </label>
        ))}
      </div>
      <button disabled={!ready} onClick={authorize}
        className="mt-3 h-9 w-full rounded-md bg-emerald-600 text-sm font-medium text-white hover:bg-emerald-700 disabled:cursor-not-allowed disabled:bg-slate-300">
        {authorizedAt ? `Authorized at ${authorizedAt}` : ready ? "Authorize deployment" : `Tick all 4 gates (${gates.filter(Boolean).length} of 4)`}
      </button>
      <Source>Authorizing records the decision in this browser only. Nothing is sent: the DBA runs migration.sql with psql, and the gateway runs nothing on pg-prod.</Source>
    </>
  );
}

export const SHEETS: Record<StageId, () => React.ReactElement> = {
  source: SourceSheet, gateway: GatewaySheet, miner: MinerSheet, gnn: GnnSheet, rl: RlSheet, llm: LlmSheet, twin: TwinSheet, dba: DbaSheet,
};

export function Inspector() {
  const { selected, drawerOpen, select, toggleDrawer } = useRun();
  const [min, setMin] = useState(false);
  const [wide, setWide] = useState(false);
  const i = STAGES.findIndex((s) => s.id === selected);
  const id = STAGES[Math.max(i, 0)].id;
  const Sheet = SHEETS[id];
  const light = "size-3 rounded-full border border-black/10";
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => e.key === "Escape" && drawerOpen && select(null);
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [drawerOpen, select]);
  return (
    <aside
      aria-hidden={!drawerOpen}
      inert={!drawerOpen}
      className={cn(
        "glass-strong absolute bottom-3 right-3 top-3 lg:top-[76px] z-30 flex flex-col overflow-hidden rounded-xl transition-all duration-200",
        wide ? "w-[min(860px,calc(100%-24px))]" : "w-[min(520px,calc(100%-24px))]",
        min && "bottom-auto h-11",
        drawerOpen ? "translate-x-0 opacity-100" : "pointer-events-none translate-x-8 opacity-0",
      )}
    >
      <header className="flex h-11 shrink-0 items-center gap-3 border-b border-slate-200/70 px-3">
        <div className="flex gap-1.5">
          <button className={cn(light, "bg-[#EF4444]")} onClick={toggleDrawer} title="Close" aria-label="Close inspector" />
          <button className={cn(light, "bg-[#F59E0B]")} onClick={() => setMin(!min)} title={min ? "Restore" : "Minimize"} aria-label="Minimize inspector" />
          <button className={cn(light, "bg-[#10B981]")} onClick={() => setWide(!wide)} title={wide ? "Narrow" : "Widen"} aria-label="Widen inspector" />
        </div>
        <div className="flex-1 truncate text-center text-sm font-semibold text-slate-900">
          <span className="mr-1.5 font-mono text-xs font-normal text-slate-400">{Math.max(i, 0) + 1}/8</span>
          {STAGES[Math.max(i, 0)].title}
        </div>
        <div className="flex">
          <button className="grid size-7 place-items-center rounded-md text-slate-600 hover:bg-slate-900/5 disabled:opacity-30" disabled={i <= 0} onClick={() => select(STAGES[i - 1].id)} aria-label="Previous stage"><ChevronLeft className="size-4" /></button>
          <button className="grid size-7 place-items-center rounded-md text-slate-600 hover:bg-slate-900/5 disabled:opacity-30" disabled={i >= STAGES.length - 1} onClick={() => select(STAGES[i + 1].id)} aria-label="Next stage"><ChevronRight className="size-4" /></button>
        </div>
      </header>
      {!min && (
        <div className="flex-1 overflow-y-auto p-4">
          <Sheet key={id} />
          <Link href={`/stages/${id}`} className="mt-6 flex items-center justify-between rounded-lg border border-slate-200 bg-white/70 px-3 py-2 text-sm font-medium text-slate-900 hover:bg-white">
            Read the {STAGES[Math.max(i, 0)].title} deep dive <ArrowRight className="size-4" />
          </Link>
        </div>
      )}
    </aside>
  );
}

/** The interactive sheet of one stage, for its deep-dive page (server pages pass the id only). */
export function StageSheet({ id }: { id: StageId }) {
  const Sheet = SHEETS[id];
  return <Sheet />;
}
